Hotel/hotel_management/booking/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('hotel/<int:hotel_id>/rooms/', views.RoomListView.as_view(), name='room_list'),
    path('room/<int:room_id>/book/', views.RoomBookingView.as_view(), name='book_room'),
    path('bookings/', views.booking_list, name='booking_list'),
    path('accounts/register/', views.register, name='register'),
    path('accounts/login/', views.login_view, name='login_view'),
    path('accounts/profile/', views.profile_view, name='profile_view'),
    path('logout/', views.logout_view, name='logout_view'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hotel/hotel_management/hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/register/', auth_views.LogoutView.as_view(), name='logout'),
]

Hotel/hotel_management/booking/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.username}'


class Hotel(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    min_price_per_night = models.DecimalField(max_digits=6, decimal_places=2, default=100.00)
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=1.0)
    image = models.ImageField(upload_to='hotel_images/', default='hotel_images/mrs-hotel.jpg')
    address = models.CharField(max_length=300)

    def __str__(self):
        return f'{self.name}'


class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='rooms')
    room_type = models.CharField(max_length=16, default='normal')
    image = models.ImageField(upload_to='room_images/', default='room_images/hilton-room.jpeg')
    price_per_night = models.DecimalField(max_digits=6, decimal_places=2)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.hotel.name}"


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='bookings')
    start_date = models.DateField()
    end_date = models.DateField()
    guest_name = models.CharField(max_length=30, default='Guest')

    def __str__(self):
        return f"Booking by {self.guest_name} ({self.user.username}) from {self.start_date} to {self.end_date}"

Hotel/hotel_management/booking/forms.py
from django import forms
from .models import Hotel, Room, Booking, CustomUser
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        max_length=150,
        required=True,
    )

    class Meta:
        model = CustomUser
        fields = ["username",
                  "email",
                  "first_name",
                  "last_name",
                  "password1",
                  "password2"]

    def clean_username(self):
        username = self.cleaned_data.get('username')

        return username

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        return password1

    def clean_password2(self):
        password2 = self.cleaned_data.get('password2')

        return password2


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['user', 'room', 'start_date', 'end_date', 'guest_name']


class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ['name', 'description', 'address', 'min_price_per_night', 'rating', 'image']


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['hotel', 'price_per_night', 'is_available', 'image']

Hotel/hotel_management/booking/views.py
from datetime import datetime

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Hotel, Room, Booking, CustomUser
from .forms import HotelForm, RoomForm, BookingForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout
from .forms import CustomUserCreationForm
from django.views import View
from django.contrib import messages


def index(request):
    search_query = request.GET.get('search')
    if search_query:
        hotels = Hotel.objects.filter(name__icontains=search_query)
    else:
        hotels = Hotel.objects.all()
    return render(request, 'booking/index.html', {'hotels': hotels})


@login_required
def profile_view(request):
    return render(request, 'registration/profile.html')


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_view')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('profile_view')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER', 'index'))


class RoomListView(View):
    def get(self, request, hotel_id):
        hotel = get_object_or_404(Hotel, id=hotel_id)
        rooms = hotel.rooms.all()
        return render(request, 'booking/room_list.html', {'hotel': hotel, 'rooms': rooms})


class RoomBookingView(View):
    def get(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        return render(request, 'booking/book_room.html', {'room': room})

    def post(self, request, room_id):
        room = get_object_or_404(Room, id=room_id)
        user = request.user

        guest_name = request.POST.get("guest_name")
        check_in = request.POST.get("check_in")
        check_out = request.POST.get("check_out")

        check_in_date = datetime.strptime(check_in, '%Y-%m-%d').date()
        check_out_date = datetime.strptime(check_out, '%Y-%m-%d').date()

        if check_in_date >= check_out_date:
            messages.error(request, "Дата виїзду повинна бути пізніше дати заїзду.")
            return redirect('book_room', room_id=room.id)

        booking = Booking(
            user=user,
            room=room,
            start_date=check_in_date,
            end_date=check_out_date,
            guest_name=guest_name
        )

        booking.save()

        messages.success(request, "Ви успішно забронювали кімнату!")
        return redirect('booking_list')

@login_required
def booking_list(request):
    bookings = Booking.objects.filter(user=request.user)
    return render(request, 'booking/booking_list.html', {'bookings': bookings})

Hotel/hotel_management/booking/templates/booking/book_room.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/main.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="booking-container">
    <h2>Book {{ room.name }}</h2>
    <form class="booking-form" action="{% url 'book_room' room.id %}" method="POST">
        {% csrf_token %}
        <label for="guest_name">Name:</label>
        <input type="text" id="guest_name" name="guest_name" required>

        <label for="check_in">Check-in:</label>
        <input type="date" id="check_in" name="check_in" required>

        <label for="check_out">Check-out:</label>
        <input type="date" id="check_out" name="check_out" required>

        <button type="submit">Confirm Booking</button> <!-- Змінив тут -->
    </form>
    <a href="{% url 'room_list' room.hotel.id %}" class="back-btnr">Back to Rooms</a>
</div>
</body>
</html>

Hotel/hotel_management/booking/templates/booking/booking_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Bookings</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/main.css' %}">
</head>
<body>
    <div class="success-container">
        <h2>Ви успішно забронювали кімнату!</h2>
        <p>Дякуємо за вибір нашого сервісу. Ми чекаємо на ваш візит!</p>
        <a href="{% url 'index' %}" class="back-home-btn">На головну</a>
    </div>
</body>
</html>

Hotel/hotel_management/booking/templates/booking/confirmation.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking Confirmation</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/style.css' %}">
</head>
<body>
    <header>
        <h1>Booking Confirmation</h1>
    </header>

    <section class="confirmation-details">
        <p>You have successfully booked room {{ room.number }} at {{ room.hotel.name }}.</p>
        <p>Price per night: ${{ room.price_per_night }}</p>
        <a href="{% url 'hotel_list' %}" class="back-button">Back to Hotels</a>
    </section>
</body>
</html>

Hotel/hotel_management/booking/templates/booking/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Готелі Львова</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/main.css' %}">
</head>
<body>
     <header class="header">
        <div class="logo">
            <img src="{% static 'booking/img/five-stars.png' %}" alt="">
        </div>
        <form action="{% url 'index' %}" method="GET" class="search-form">
            <input type="text" name="search" placeholder="Enter hotel name...">
            <button type="submit">Search</button>
        </form>
        <div class="auth-buttons">
        {% if user.is_authenticated %}
            <span class="username">Welcome, {{ user.username }}!</span>
            <form action="{% url 'logout_view' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="logout-btn">Logout</button>
            </form>
        {% else %}
            <button class="login-btn"><a href="{% url 'login_view' %}">Login</a></button>
            <button class="register-btn"><a href="{% url 'register' %}">Register</a></button>
        {% endif %}
        </div>
    </header>
    <div class="hotel-list">
        <h2>Best Hotels in Lviv</h2>
        <ul>
            {% for hotel in hotels %}
            <li class="hotel-item">
                <img src="{{ hotel.image.url }}" alt="{{ hotel.name }}">
                <div class="hotel-details">
                    <h3>{{ hotel.name }}</h3>
                    <p>{{ hotel.description }}</p>
                    <p>Rating: {{ hotel.rating }} / 5</p>
                    <p>Starting from ${{ hotel.min_price_per_night }} per night</p>
                    <a href="{% url 'room_list' hotel.id %}" class="details-button">View Rooms</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

Hotel/hotel_management/booking/templates/booking/room_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кімнати у {{ hotel.name }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/main.css' %}">
</head>
<body>
    <h2 class="section-title">Rooms</h2>
    <div class="button-container">
        <a href="{% url 'index' %}" class="back-btn">Go back to hotels</a>
        <div class="auth-buttons">
            {% if user.is_authenticated %}
            {% else %}
            <a href="{% url 'login' %}" class="btn">Login</a>
            <a href="{% url 'register' %}" class="btn">Register</a>
            {% endif %}
        </div>
    </div>

    <ul class="room-list">
        {% for room in rooms %}
        <li class="room-item">
            <img src="{{ room.image.url }}" alt="{{ room.name }}">
            <p>Type: {{ room.room_type }}</p>
            <p>Price: ${{ room.price_per_night }} per night</p>

            {% if user.is_authenticated %}
            <button class="book-btn"><a href="{% url 'book_room' room.id %}">Reserve</a></button>
            {% else %}
            <button class="book-btn disabled" disabled>Log in to Reserve</button>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</body>
</html>